src/Entity/Stock.php
<?php

namespace App\Entity;

use App\Repository\StockRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StockRepository::class)
 */
class Stock
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_stock;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte_alerte;

    /**
     * @ORM\OneToOne(targetEntity=Produit::class, inversedBy="stock", cascade={"persist", "remove"})
     */
    private $produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQteStock(): ?int
    {
        return $this->qte_stock;
    }

    public function setQteStock(int $qte_stock): self
    {
        $this->qte_stock = $qte_stock;

        return $this;
    }

    public function getQteAlerte(): ?int
    {
        return $this->qte_alerte;
    }

    public function setQteAlerte(int $qte_alerte): self
    {
        $this->qte_alerte = $qte_alerte;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }


}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="app_accueil")
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        $produits = $produitRepository->findAll();


        return $this->render('accueil/index.html.twig', compact('produits'));
    }
}

templates/accueil/index.html.twig
{% extends "Base.html.twig" %}

{% block title%} Shopping | Accueil {% endblock %}

{% block body %}
    <h1 class="titre">Accueil</h1>
    <div class="row">
    {% for produit in produits %}     
        <article class="article">
            <h2>{{ produit.nom }}</h2>
            <p><span>Prix : </span>{{ produit.prix }}</p>
            {# <p><span>Disponible : {{ produit.stock.qteStock }}</span></p> #}

        </article>
    {% endfor %}
    </div>
{% endblock %}